# Generated by Django 4.1.4 on 2022-12-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteBasicDeatails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
