# Generated by Django 4.1.4 on 2022-12-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_countries_country_name_states_jobs_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
    ]
