# Generated by Django 4.1.4 on 2022-12-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_city_name_city_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='country_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='states',
            old_name='state_name',
            new_name='name',
        ),
    ]
