# Generated by Django 4.1.4 on 2022-12-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_company_place_jobs_company_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtypeshift',
            name='created_id',
        ),
        migrations.RemoveField(
            model_name='jobtypeshift',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobtypeshift',
            name='modified_id',
        ),
        migrations.DeleteModel(
            name='JobTypes',
        ),
        migrations.DeleteModel(
            name='JobTypeShift',
        ),
    ]
