# Generated by Django 4.1.4 on 2022-12-11 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modified_id',
        ),
    ]
