# Generated by Django 4.1.4 on 2022-12-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_created_id_remove_user_modified_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='created_id',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='modified_id',
        ),
    ]
